### ISSUE TITLE
Allow Google Map embeds in WYSIWYG

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_profile#109]
This was requested by Jamie Jones. We should follow up with her to determine if sitenow_maps could meet this need.

**Comment by adamdelaney** [comment]
This could be possible with embed.ly. There is a google maps provider: http://embed.ly/provider/googlemaps

**Comment by genjohnson** [comment]
﻿Marking as "wontfix", but this could be re-opened later if needed.
