### ISSUE TITLE
Webmasters have "Bypass access" permission for nodes

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_profile#123]
Investigate why Webmasters have this permission as it bypasses all access checks, which could be an issue. If we do not have a good reason for this permission configuration, we should remove this access from the webmaster role.

**Comment by genjohnson** [comment]
I think this permission was granted so that webmasters could access unpublished nodes that they did not create.

**Comment by adamdelaney** [comment]
I cannot get `sitenow_featured_slider` to revert. It seems like the view any unpublished featured_slider content permission is in the features UI, but has been exported to code.

**Comment by adamdelaney** [comment]
Opened a new issue for the overridden bug, see #133
