### ISSUE TITLE
Update support article screenshots

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/sitenow_standard_profile#135]
**Articles that include screenshots of the admin theme:**
- [ ] [Advanced webform configuration](https://its.uiowa.edu/support/article/107376)
- [ ] [Masquerade as another user](https://its.uiowa.edu/support/article/105215)
- [ ] [Viewing and reverting changes to content](https://its.uiowa.edu/support/article/103524)
- [ ] [Using the SiteNow Background Image App with the Stellar Theme](https://its.uiowa.edu/support/article/104335)
- [ ] [Using Find Text](https://its.uiowa.edu/support/article/105109)
- [ ] [Transferring ownership of a website](https://its.uiowa.edu/support/article/103500)
- [ ] [Promoting content to show on the homepage](https://its.uiowa.edu/support/article/105172)
- [ ] [Navigating using the 'back to site' button](https://its.uiowa.edu/support/article/104176)
- [ ] [Creating URL redirects](https://its.uiowa.edu/support/article/104286)
- [ ] [How to change the order of People](https://its.uiowa.edu/support/article/102634)
- [ ] [Editing published date of SiteNow Articles](https://its.uiowa.edu/support/article/103966)
- [ ] [Deleting a user account](https://its.uiowa.edu/support/article/104245)
- [ ] [Cropping images](https://its.uiowa.edu/support/article/102768)
- [ ] [Creating a menu link to a page](https://its.uiowa.edu/support/article/102630)
- [ ] [Changing the order of menu links](https://its.uiowa.edu/support/article/102631)
- [ ] [Changing the URL of a page](https://its.uiowa.edu/support/article/104241)
- [ ] [Changing the site logo](https://its.uiowa.edu/support/article/102823)
- [ ] [Changing the roles of user accounts](https://its.uiowa.edu/support/article/103157)
- [ ] [Changing the order of Callouts in a slideshow or grid](https://its.uiowa.edu/support/article/104139)
- [ ] [Changing the order of taxonomy terms](https://its.uiowa.edu/support/article/102638)
- [ ] [Changing the display settings of a theme](https://its.uiowa.edu/support/article/102766)
- [ ] [Adding a user account](https://its.uiowa.edu/support/article/103061)
- [ ] [Adding Google Analytics to SiteNow](https://its.uiowa.edu/support/article/103281)
- [ ] [Finding and managing files](https://its.uiowa.edu/support/article/102767)
- [ ] [Finding and editing content in SiteNow](https://its.uiowa.edu/support/article/102038)
- [ ] [Understanding and using SiteNow editing tools](https://its.uiowa.edu/support/article/105169)
- [ ] [Creating content](https://its.uiowa.edu/support/article/105168)
- [ ] [Getting to know the buttons](https://its.uiowa.edu/support/article/105165)

**Articles that require other content updates:**
- [ ] [How to remove demo content](https://its.uiowa.edu/support/article/102640)
- [x] [How to reinstate demo content](https://its.uiowa.edu/support/article/102639) - this article can be deleted
- [ ] [Creating a menu link to an external URL](https://its.uiowa.edu/support/article/102632) - copy how to select parent and change weight from https://its.uiowa.edu/support/article/102630
- [x] [Changing the theme](https://its.uiowa.edu/support/article/102765) - add note that disabled themes appear muted until hovered over

**Comment by genjohnson** [comment]
Closing this issue. For now we'll update documentation on an as-needed basis.
