### ISSUE TITLE
Configure "to" address of contact form in support dashboard & test sending to Help Desk

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/sitenow_standard_profile#146]

**Comment by genjohnson** [comment]
This needs to be tested on dev.

I've tried sending a request from uiowa.dev.drupal.uiowa.edu/staff. The drupal logs indicate the email was sent but I do not see the ticket in Support Center.

**Comment by genjohnson** [comment]
This is working as expected. There can be delays in the emails being received, which seems to be what happened with the test this morning.
