### ISSUE TITLE
[Lab theme] Flex bug in IE11

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_profile#154]
Flex is being used to position branding elements in the Lab theme, and there is a bug in IE 11 with handing `min-height` on flex containers that is causing lots of extra vertical space in the `.l-branding` section. 

Details about this bug and a workaround are available at https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items.

**Comment by adamdelaney** [comment]
This looks like an issue with `flex-direction: column`. The flex implementation is used to vertically center the branding elements so I don't believe we need to set the flex direction. I have removed the css declaration.
