### ISSUE TITLE
Remove localist_pane module

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_profile#171]
Since sites have been switched to uiowa_events module, localist_pane can be removed.
- [x] Remove CSS in each theme for localist_pane (optional)
- [x] Disable & uninstall localist_pane
- [x] Remove localist_pane from the uiowa_standard_profile make file

**Comment by richardbporter** [comment]
4ac3339 will need to be deployed first before disabling/uninstalling.

**Comment by richardbporter** [comment]
I've disabled and uninstalled the module for all production sites.
