### ISSUE TITLE
add transliteration

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/sitenow_standard_profile#20]
- [ ] add to makefile
- [ ] add as dependency
- [ ] update hook to turn it on

**Comment by richardbporter** [comment]
`Transliteration has been installed. Fix existing file names. `

I'm guessing we don't want to do this because it will break any hard-coded links.

**Comment by brandonneil** [comment]
Yea I don't think we should fix existing.

On Apr 25, 2017, at 3:21 PM, Richard B. Porter <notifications@github.com<mailto:notifications@github.com>> wrote:


Transliteration has been installed. Fix existing file names.

I'm guessing we don't want to do this because it will break any hard-coded links.
