### ISSUE TITLE
Move standard modules directly into profile

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/sitenow_standard_profile#28]
The following custom modules are only used in the standard profile and could be moved into this repo to ease management of the code:

- sitenow_apps
- sitenow_footer
- sitenow_ownership
- sitenow_social_media
- sitenow_articles
- sitenow_core
- sitenow_entity_view_modes
- sitenow_events
- sitenow_featured_slider
- sitenow_forms
- sitenow_navigation
- sitenow_pages
- sitenow_people
- sitenow_seo

The benefit of this would be removing the need to tag a release of that repo and updating the make here. Saves a step and time.

Issues to consider: Some Custom Service sites could be using these modules, and keeping them in separate repos could make updating the code in those sites easier. Perhaps we identify what custom sites are using these modules (sitenow_people and sitenow_articles come to mind) and we could decide to keep those as separate repos.

**Comment by richardbporter** [comment]
I know there are a few custom sites using these but they've been copied into the site repo and probably overridden, changed, etc. I doubt any have been updated - they were probably used as a starting point for a feature.

**Comment by richardbporter** [comment]
Could we also do this for:

- engineering_standard

- sitenow_standard_uiowa_theme

- sitenow_standard_student_org_theme

- sitenow_standard_base_theme

- sitenow_standardtheme

**Comment by brandonneil** [comment]
I'm all for moving these into this profile, but we probably shouldn't delete the repos until we have shut down all the on-prem servers, since those are used there.

**Comment by richardbporter** [comment]
I'm not loving the solution I came up with in https://github.com/ITS-UofIowa/sitenow_custom_profile/pull/61. I did that to avoid listing each path in the .gitignore file but forgot that we might want to scan the code on Travis builds. That would have to be done on a path-by-path basis now. Ugh.

I hate to admit it but a subdirectory solution be the best option. For example, `modules/sitenow/*` and `themes/sitenow` are tracked in VCS. That can be easily handled in the .gitignore and Travis builds.

What do you think? This might impact #27. Would a registry rebuild be necessary for sites?

**Comment by brandonneil** [comment]
I bet a registry rebuild would be necessary.

**Comment by richardbporter** [comment]
Unresolved issues/PR's/branches:

- [ ] https://github.com/ITS-UofIowa/sitenow_core/pull/8
- [ ] https://github.com/ITS-UofIowa/sitenow_people/tree/pharmacy
- [ ] https://github.com/ITS-UofIowa/sitenow_standard_lab_theme/issues/39
- [ ] https://github.com/ITS-UofIowa/sitenow_standard_lab_theme/issues/38
- [ ] https://github.com/ITS-UofIowa/sitenow_articles/tree/migrate

**Comment by briand44** [comment]
I deleted the pharmacy branch of sitenow_people.

**Comment by genjohnson** [comment]
I've closed https://github.com/ITS-UofIowa/sitenow_core/pull/8

**Comment by richardbporter** [comment]
Migrate branch of sitenow_articles has no commits ahead of 7.x-1.x.
