### ISSUE TITLE
Trying to get property of non-object in sitenow_core_user_is_admin()

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/sitenow_standard_profile#44]
Whence logging in via uli to a standard service site via ```drush uli --uri=https://uiowa.edu.dd:8084/university-shared-services btneil``` I get the following notice:
```
Notice: Trying to get property of non-object in sitenow_core_user_is_admin() (line 321 of /Users/btneil/acquia/uiowa701/docroot/profiles/sitenow_standard_profile/modules/features/sitenow_core/sitenow_core.module).
```

**Comment by briand44** [comment]
I think I have seen this error as well when running db updates from update.php

**Comment by richardbporter** [comment]
See: https://github.com/ITS-UofIowa/sitenow_core/issues/10
