### ISSUE TITLE
[sitenow_standard_lab_theme] Transparency overlay color being validated when "no transparency overlay" is selected

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_profile#57]
In the theme settings for the sitenow_standard_lab_theme, the color of the site name is validated against its immediate background (a box behind it or the transparency overlay) to be sure that the elements are different colors (we don't want white text on a white background or black text on a black background).

However, if "no transparency overlay" is selected, the color of the site name is still compared to the selected transparency overlay color (this field is hidden when "no transparency overlay" is selected) and the form will fail validation if the colors are the same.

Instead, it is expected that this validation check not run when "no transparency overlay" is selected.

**Comment by richardbporter** [comment]
This was fixed in #54.
