### ISSUE TITLE
July 2017 Updates

### ISSUE THREAD

**Issue by briand44** [ITS-UofIowa/sitenow_standard_profile#80]
Acquia Connector 7.x-2.17 -> [7.x-3.1](https://www.drupal.org/project/acquia_connector/releases/7.x-3.1)
Apps 7.x-1.0 -> [7.x-1.1](https://www.drupal.org/project/apps/releases/7.x-1.1)
Automatic Entity Label 7.x-1.3 -> [7.x-1.4](https://www.drupal.org/project/auto_entitylabel/releases/7.x-1.4)
File Entity 7.x-2.0-beta3 -> [7.x-2.2](https://www.drupal.org/project/file_entity/releases/7.x-2.2)
Media 7.x-2.4 -> [7.x-2.8](https://www.drupal.org/project/media/releases/7.x-2.8)
Media: YouTube 7.x-3.0 -> [7.x-3.4](https://www.drupal.org/project/media_youtube/releases/7.x-3.4)
Module Filter 7.x-2.0 -> [7.x-2.1](https://www.drupal.org/project/module_filter/releases/7.x-2.1)
Node Revision Delete 7.x-2.6 -> [7.x-2.7](https://www.drupal.org/project/node_revision_delete/releases/7.x-2.7)
Pathologic 7.x-2.12 -> [7.x-3.1](https://www.drupal.org/project/pathologic/releases/7.x-3.1)
Site verification 7.x-1.1 -> [7.x-1.2](https://www.drupal.org/project/site_verify/releases/7.x-1.2)
Wysiwyg 7.x-2.2+54-dev -> [7.x-2.4](https://www.drupal.org/project/wysiwyg/releases/7.x-2.4)

**Comment by richardbporter** [comment]
#82 will be included in this.
