### ISSUE TITLE
Add Callout functionality

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_profile#86]
Using the Slideshow Item content type, add a view display that is a grid of items.

**Comment by genjohnson** [comment]
I met with the sponsor of this feature yesterday and the only request/feedback they have is to be able to choose how many callouts display per row.

@richardbporter has volunteered to help with this :)

**Comment by genjohnson** [comment]
Work for this feature is being done on the branch [f/86-callouts](https://github.com/ITS-UofIowa/sitenow_standard_profile/tree/f/86-callouts)

**Comment by adamdelaney** [comment]
I have added the column config and css for column layout control. Please test and let me know.

**Comment by genjohnson** [comment]
Yay, thank you! I'll take a look tomorrow :)
