### ISSUE TITLE
Page title default and permissions change

### ISSUE THREAD

**Issue by dhannad** [ITS-UofIowa/sitenow_standard_profile#87]
A number of standard sites have "duplicate page title" errors in Google Webmaster tools due to the Page Title module being enabled and the default title entered as a text version of the site name.
Proposed actions:
- Check to see if page_title module is enabled. If so...
-- set default page title to be the current page title | site name, using tokens.
-- change permissions so that only administrator has default access to page_title.
(Note: page_title is an older module, more recently created sites use metatag)

**Comment by dhannad** [comment]
Discussion within group suggested removing page_title module and instead use metatag module.

**Comment by genjohnson** [comment]
distance.uiowa.edu is an example of a site using the advanced permissions option of the Metatag module to control access to individual fields on nodes.
