### ISSUE TITLE
Add help/support dashboard

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/sitenow_standard_profile#91]
Add a button in the admin toolbar for users to get help. This should include access to support articles and a form that will create a ticket with the ITS Help Desk.

**Access to support articles**
I am envisioning a page which lists the titles of support articles grouped by category that link to the articles on the ITS website. Ideally we could coordinate with Adrienne to create a feed from the ITS website of support articles per info center which we could consume to generate these lists.

**Form to create a ticket**
This will need more discussion with the ITS Help Desk staff to determine how to implement this. Should these tickets be automatically escalated to the SiteNow Standard/Web Services team?

**Comment by genjohnson** [comment]
I've started work on this in https://github.com/its-uofiowa/sitenow_standard_profile/tree/support_dashboard

For now there are two variables that need to be configured to test the contact form:
sitenow_support_contact_form_from_email and sitenow_support_contact_form_to_email

We might be able to hard-code these email addresses, but it's nice being able to change them for testing on various environments.

I talked with Jamie Matthews about the feature to create a ticket, and there's a specific email address we will need to have the support requests send to. When I know what that email address is I'll post it here.

**Comment by genjohnson** [comment]
Data to get out of the ITS website for Support Article nodes (argument for Info Center):
- Title
- URL to node page
- Keywords
- Category

**Comment by genjohnson** [comment]
I've emailed Adrienne asking if we can add this feed to the ITS website and am waiting on a response before we proceed.

**Comment by genjohnson** [comment]
We have approval from Adrienne to proceed :)

**Comment by adamdelaney** [comment]
I have a json feed in dev at: https://its.dev.drupal.uiowa.edu/api/v1.0/support-articles/100028
